Repository Mapsui/Mapsui, pull requests merged in 2025-09, with the labels that each got.

#3107 Use MinimalRenderFetchStrategy in RasterizingTileLayer
  Mapsui.Tiling/Layers/RasterizingTileLayer.cs
  Mapsui.Tiling/Rendering/TilingRenderFetchStrategy.cs
Labels: PR type: ♻️ Refactor

#3135 Fix the 'too many pixels' check
  Mapsui/Extensions/MSectionExtensions.cs
Labels: PR type: 🛠️ Maintenance

#3139 Update Microsoft.WindowsAppSDK to a1.6.250602001
  Mapsui.UI.WinUI/Mapsui.UI.WinUI.csproj
  Mapsui.UI.Wpf/Mapsui.UI.Wpf.csproj
Labels: PR type: 📦 Update

#3149 Enable GPU by default on MAUI 9 again
  Mapsui.UI.Maui/MapControl.cs
  Mapsui.UI.WindowsForms/MapControl.cs
Labels: PR type: 🚀 Feature
