Repository Mapsui/Mapsui, pull requests merged in 2025-06, with the labels that each got.

#3042 Update the version of VexTile.TileSource.Mvt to 1.0.2 in our sample
  .github/workflows/dotnet.yml
  Directory.Packages.props
  Samples/Mapsui.Samples.Common/Maps/Tiles/VexTileMvtSample.cs
  Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI/Platforms/Android/Resources/values/Styles.xml
Labels: PR type: 🧪Sample

#3043 Make AnimatedPointSample animate on start
  Mapsui/Layers/AnimatedLayers/AnimatedPointLayer.cs
  Samples/Mapsui.Samples.Common/Maps/Animations/AnimatedPointsSample.cs
  Samples/Mapsui.Samples.Common/Maps/Animations/AnimatedPointsSampleProvider.cs
  Samples/Mapsui.Samples.Wpf/Window1.xaml.cs
Labels: PR type: 🧪Sample

#3036 Update Avalonia to 11.3.1
  Directory.Packages.props
Labels: PR type: 📦 Update

#3016 Adds outline support to LineString
  Mapsui.Rendering.Skia/SkiaStyles/LineStringRenderer.cs
  Mapsui/Styles/VectorStyle.cs
  Samples/Mapsui.Samples.Common/Maps/DataFormats/WfsSample.cs
  Samples/Mapsui.Samples.Common/Maps/Demo/InfoLayersSample.cs
  Samples/Mapsui.Samples.Common/Maps/Editing/EditingSample.cs
  Samples/Mapsui.Samples.Common/Maps/Geometries/LineStringSample.cs
  Samples/Mapsui.Samples.Common/Maps/Performance/RasterizingLayerWithLineStringSample.cs
  Samples/Mapsui.Samples.Common/Maps/Performance/RasterizingLayerWithPointsSample.cs
  Samples/Mapsui.Samples.Common/Maps/Performance/RasterizingTileLayerWithLineStringSample.cs
  Samples/Mapsui.Samples.Common/Maps/Performance/RasterizingTileLayerWithPointsSample.cs
  Samples/Mapsui.Samples.Common/Maps/Projection/MultiPolygonProjectionSample.cs
  Samples/Mapsui.Samples.Common/Maps/Styles/LabelsSample.cs
  Samples/Mapsui.Samples.Common/Maps/Styles/OpacityStyleSample.cs
  Samples/Mapsui.Samples.Common/Maps/Styles/PenStrokeCapSample.cs
  Samples/Mapsui.Samples.Common/Maps/Styles/SymbolsSample.cs
  Samples/Mapsui.Samples.Common/Maps/WFS/Wfs2_0Sample.cs
  Samples/Mapsui.Samples.Common/Maps/WFS/WfsOgcFilterSample.cs
  Samples/Mapsui.Samples.Common/Maps/WFS/WfsPointsSample.cs
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/GeometryCollectionSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/GeometryCollectionTestSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/LineStringSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/OpacityStyleSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/PenStrokeCapSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/RasterizingLayerWithLineStringSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalRegression/RasterizingTileLayerWithLineStringSample.Regression.png
  Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/OriginalTest/geometry_collection.png
  Tests/Mapsui.Tests.Common/Maps/LineSample.cs
  Tests/Mapsui.Tests.Common/Maps/PointInWorldUnitsSample.cs
  Tests/Mapsui.Tests.Common/Maps/PolygonTestSample.cs
  Tests/Mapsui.Tests.Common/Maps/ProjectionTestSample.cs
  Tests/Mapsui.Tests.Common/Maps/StackedLabelsTestSample.cs
Labels: PR type: 🚀 Feature

#3044 Upping dotnet sdk to 9.0.301
  .github/workflows/dotnet-docs.yml
  .github/workflows/dotnet-release-nugets.yml
  .github/workflows/dotnet.yml
  global.json
Labels: PR type: 🔧 Infrastructure

#3039 Adds current Viewport to ViewportChangedEventArgs
  Mapsui/Navigator.cs
  Mapsui/ViewportChangedEventArgs.cs
  Tests/Mapsui.Tests/NavigatorTests.cs
Labels: PR type: 🚀 Feature

#3035 Use the new slnx Format instead of the sln for the Solution File.
  .github/workflows/dotnet-release-nugets.yml
  .github/workflows/dotnet.yml
  .husky/task-runner.json
  Mapsui.Android.slnf
  Mapsui.Avalonia.slnf
  Mapsui.Benchmarks.slnf
  Mapsui.Blazor.slnf
  Mapsui.Eto.slnf
  Mapsui.Linux.slnf
  Mapsui.Mac.slnf
  Mapsui.Maui.slnf
  Mapsui.Tests.slnf
  Mapsui.Uno.slnf
  Mapsui.WinUI.slnf
  Mapsui.WindowsForms.slnf
  Mapsui.Wpf.slnf
  Mapsui.iOS.slnf
  Mapsui.sln
  Mapsui.slnx
  docs/general/markdown/rendering-tests.md
Labels: PR type: 🧰 Maintenance
